Разобрал обсуждение с заказчиком, ч. 1; поправил некоторые требования
karpoftea/mts-kata-2023 pull request #23
Opened 2023-10-04 16:10 UTC by slavacestmoi

2023-10-04 17:27 UTC, karpoftea requested changes

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +  - [Бизнес-контекст (BR)](#бизнес-контекст-br)
Давай на русском сделаем аббревиатуры, у нас же все остальные уже на русском

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +| Масштаб и ограничения MVP | <ul><li>Срок сдачи - 1 июля 2024 г.</li><li>На момент релиза будет доступно 20 образовательных курсов, а также старый контент (с текущего решения от вендора).</li><li>До
Вроде срок сдачи 1.09. Они вроде говорили про 9 месяцев (это точно) начиная со след года (это не точно). Может просто написать что есть 9 мес?

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +| ОГ.008     | Компоненты | В разработке используются, разрешенные \ принятые в МТС компоненты | MVP |
Вот сюда имеет смысл написать про 9 мес

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +| СД.001 | Переноса контента (структура и описание курсов, данные пользователей) из реляционной СУБД (текущей реализации от вендора) текущей реализации в новую систему | Миграция | MVP |
Кроме этого должны уметь отображать все те вариации материалов, которые уже есть с контентом который уже есть. А еще должны перетащить домашки, дипломы и тп.

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +| ~~ПП.001~~ | Ограничивать кол-во студентов на курсе | Управление курсами | Снято в связи с ответом "Ограничения по студентам на курсе" |
А можем тут сослаться на другое фт, чтобы не искать в ответах?

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
>  | ПП.002 | Добавлять курс, а также его дочерние элементы с учебными материалами (в т. ч. редактировать их, управлять их порядком) | Управление курсами |
Кстати я так понял что преподы вообще не влияют на организацию материала курса, а только проверяют дипломные работы и проводят активности. Имеет смысл убрать тут требования об управлении курсами и материалами?

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +| Г.202 | Доступа к маркетинговым материалам: записанные видео доступны для просмотра в любое время | Управление материалами курсов | MVP |
А для остальных где версия)))?

2023-10-04 17:27 UTC, karpoftea commented on docs/requirements/requirements.md
> +| ПП.101 | Получать уведомления о появлении готовых к проверке домашних заданий по его курсу, назначенных ему студентов | Управление уведомлениями | MVP |
Я так понял что домашки могут быть проверены автоматом, но не все. Дипломные вручную. Надо в фт указать что неуоторые домашки нужно проверить автоматом

2023-10-04 21:21 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +  - [Бизнес-контекст (BR)](#бизнес-контекст-br)
В следующем обновлении учту

2023-10-04 21:23 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +| ~~ПП.001~~ | Ограничивать кол-во студентов на курсе | Управление курсами | Снято в связи с ответом "Ограничения по студентам на курсе" |
Поправлю

2023-10-04 22:00 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +| Масштаб и ограничения MVP | <ul><li>Срок сдачи - 1 июля 2024 г.</li><li>На момент релиза будет доступно 20 образовательных курсов, а также старый контент (с текущего решения от вендора).</li><li>До
Да, поправил сентябрь.

2023-10-04 22:02 UTC, slavacestmoi commented on docs/requirements/requirements.md
>  | ПП.002 | Добавлять курс, а также его дочерние элементы с учебными материалами (в т. ч. редактировать их, управлять их порядком) | Управление курсами |
Да, убрал

2023-10-04 22:02 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +| Г.202 | Доступа к маркетинговым материалам: записанные видео доступны для просмотра в любое время | Управление материалами курсов | MVP |
Не все прошел, только разобрал ответы

2023-10-04 22:03 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +| ПП.101 | Получать уведомления о появлении готовых к проверке домашних заданий по его курсу, назначенных ему студентов | Управление уведомлениями | MVP |
Добавил

2023-10-04 22:03 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +| СД.001 | Переноса контента (структура и описание курсов, данные пользователей) из реляционной СУБД (текущей реализации от вендора) текущей реализации в новую систему | Миграция | MVP |
Не все внес, только разобрал ответы

2023-10-04 22:06 UTC, slavacestmoi commented on docs/requirements/requirements.md
> +| ОГ.008     | Компоненты | В разработке используются, разрешенные \ принятые в МТС компоненты | MVP |
Не, это пишут в "Масштаб и ограничения..." версий

2023-10-04 22:07 UTC, slavacestmoi commented
Поправил  многое

2023-10-05 05:07 UTC, karpoftea approved these changes

2023-10-05 05:07 UTC, merged